---
abstract: 'Template::Toolkit with automatic filtering'
author:
  - 'Christian Walde <walde.christian@googlemail.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::InDistDir: 0
  Test::More: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200013, CPAN::Meta::Converter version 2.110930'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-AutoFilter
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Template::AutoFilter:
    file: lib/Template/AutoFilter.pm
    version: 0.112070
  Template::AutoFilter::Parser:
    file: lib/Template/AutoFilter/Parser.pm
    version: 0.112070
requires:
  Template: 0
  Template::Parser: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Template-AutoFilter
  homepage: https://github.com/wchristian/Template-AutoFilter
  repository: https://github.com/wchristian/Template-AutoFilter
version: 0.112070
